Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Car_Store.models;
using System.Data;
using System;
using static Org.BouncyCastle.Asn1.Cmp.Challenge;
using System.Xml.Linq;

namespace Car_Store.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;
        private readonly DB DB;
        [BindProperty(Name = "search")]
        public string search { get; set; }
        [BindProperty]
        public DataTable dt { get; set; }
        [BindProperty]
        public int iteratoe { get; set; }

        [BindProperty]
        public int Landing_random { get; set; }
        [BindProperty]
        public WishCart cartWish { get; set; }



        public IndexModel(ILogger<IndexModel> logger,DB db)
        {
            _logger = logger;
            DB = db;
        }
        public void OnGet()
        {
            
            Landing_random =DB.get_all_cars_count();
            dt = (DataTable)DB.get_all_cars();
        }

        public IActionResult OnPostLogout()
        {
            HttpContext.Session.Remove("User_Type");
            HttpContext.Session.Remove("User_ID");
            return RedirectToPage("/Index");
        }
        public IActionResult OnPostAddCarToCart(int PID)
        {
            if (HttpContext.Session.GetInt32("User_ID") == null)
            {
                return RedirectToPage("/SignUpIn");
            }
            else
            {
                cartWish.CId = (int)HttpContext.Session.GetInt32("User_ID");
            }
            cartWish.PId = PID;
            cartWish.typepv = 1;
            cartWish.typecw = 0;
            cartWish.insert();
            return RedirectToPage("/CartPage");
        }
        public IActionResult OnPostAddCarToWishList(int PID)
        {
            if (HttpContext.Session.GetInt32("User_ID") == null)
            {
                return RedirectToPage("/SignUpIn");
            }
            else
            {
                cartWish.CId = (int)HttpContext.Session.GetInt32("User_ID");
            }
            cartWish.PId = PID;
            cartWish.typepv = 1;
            cartWish.typecw = 1;
            cartWish.insert();
            return RedirectToPage("/Index");
        }
        public IActionResult OnPostSearch()
        {
            return RedirectToPage("/FilterPage", new { search = this.search });
        }
    }
}

Pages/Shared/ClientLayout.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Car_Store.Pages.Shared
{
    public class ClientLayoutModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

Pages/Shared/ClientLayout.cshtml
@using MyData = System.Data
@using MyDB = Car_Store.models

@{
    // Use the MyData namespace alias instead of System.Data
    MyData.DataTable table = new MyData.DataTable();
    MyDB.DB dB = new MyDB.DB();

    
}


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>TRMB cars</title>

    <!-- My Style -->
    <link rel="stylesheet" href="~/css/layout.css" asp-append-version="true">
    <!-- Nomralize Css -->
    <link rel="stylesheet" href="~/css/normalize.css" asp-append-version="true">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="~/css/all.min.css" asp-append-version="true">
    <!-- goole icons -->
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons"
          rel="stylesheet">
    <!-- My FarmeWork -->
    <link rel="stylesheet" href="~/css/framework.css" asp-append-version="true">
    <!-- Font Google -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@400;500;700;800&display=swap" rel="stylesheet">

</head>
<body>
    <header>
        <div class="container">
            <!-- Start Research -->
            <form method="post">
            <div class="head bn-flex mt-5 mr-20">
                <a style="color:black; padding-right:10px" asp-page="/Index"><h2 class="m-20 fw-bold fs-18"><i class="fa-sharp fa-solid fa-car-side" style="padding-right:10px; color: #000000"></i>TRMB cars</h2></a>
                <div class="soical d-flex">
                    <i class="fa-solid fa-user-group"></i>
                    <div style="padding-right:55px;" class="support m-0 d-flex fl-column">
                        <span class="fs-14 mb-10 cursor-pointer">Support</span>
                        <span class="c-blue fs-14">+20 101 456 1603</span>
                    </div>
                </div>
            </div>
            </form>
            <!-- End Research -->
            <!-- Start Navbar -->
            <nav class="w-full bn-flex">
                <div class="all-ctg  d-flex">
                    <div class="details Trs-05 rad-20 bg-white p-relative mt-10 mb-10 ml-40" onclick="toggleeMenu()">
                        <div class="burgra bg-blue rad-half p-absolute">
                            <span id="child1" class="bg-white Trs-03"></span>
                            <span id="child2" class="bg-white Trs-03"></span>
                            <span id="child3" class="bg-white Trs-03"></span>
                            <ul id="dropMenu" class="bg-ccc Trs-03 pt-10 pb-5 pl-10 pr-10 w-110 rad-10 mt-35" style="width:158px;">
                                
                                <li id="p-li" class="pt-10 Trs-03 pb-10 border-b">
                                    <a style="color:black;" asp-page="/Add_Car">Sell Car</a>
                                </li>
                                <li id="p-li" class="pt-10 Trs-03 pb-10 border-b">
                                    <a style="color:black;" asp-page="/FilterPage">Discover Cars</a>
                                </li>
                                <li id="p-li" class="pt-10 Trs-03 pb-10">
                                    <a style="color:black;" asp-page="/ServiceCenters">Services Center</a>
                                </li>
                                <li id="p-li" class="pt-10 Trs-03 pb-10">
                                    <a style="color:black;" asp-page="/profile">Profile</a>
                                </li>
                                <li id="p-li" class="pt-10 Trs-03 pb-10">
                                    <a style="color:black;" asp-page="/CartPage">Cart</a>
                                </li>
                                <li id="p-li" class="pt-10 Trs-03 pb-10">
                                    <a style="color:black;" asp-page="/WishList">WishList</a>
                                </li>
                                <li id="p-li" class="pt-10 Trs-03 pb-10">
                                    <input type="submit" form="logout-from" asp-page-handler="Logout" style="border:none; color:black; background-color:transparent;" value="Logout" />
                                </li>
                            </ul>
                        </div>
                        <p class="c-black pl-10 m-10 ml-30 fs-14 fw-bold">All Categores</p>
                    </div>
                    <script> 
                        function toggleeMenu() {
                            var menu = document.getElementById("dropMenu");
                            var child1 = document.getElementById("child1");
                            var child2 = document.getElementById("child2");
                            var child3 = document.getElementById("child3");
                            var Lip = document.getElementById("p-li")

                            if (menu.style.transform === "translate(-220px)") {
                                menu.style.transform = "translate(0)";
                                menu.style.overflow = "visible";
                                child1.style.transform = 'rotate(80deg)';
                                child1.style.top = '12px';
                                child1.style.width = '25px';
                                child1.style.left = '-2px';
                                child2.style.top = '15px';
                                child2.style.left = '8px';
                                child2.style.width = '20px';
                                child2.style.transform = 'rotate(-60deg)';
                                child3.style.transform = 'rotate(45deg)';
                                child3.style.left = '-5px';
                                child3.style.top = '16px';
                                child3.style.width = '20px';
                                menu.style.zIndex = '2';
                                Lip.style.zIndex = '2';
                            } else {
                                menu.style.transform = "translate(-220px)";
                                menu.style.overflow = "hidden";
                                child1.style.transform = '';
                                child1.style.top = '';
                                child1.style.left = '';
                                child1.style.width = '';
                                child2.style.transform = '';
                                child2.style.top = '7px';
                                child2.style.left = '';
                                child2.style.width = '';
                                child3.style.transform = '';
                                child3.style.top = '14px';
                                child3.style.left = '';
                                child3.style.width = '';
                            }
                        }
                        </script>
                    <div class="center-flex c-black fw-bold fs-15">
                        <a href="/FilterPage" class="pl-10 Trs-05 c-black pr-10">Discover Cars!</a>
                        <a href="/ServiceCenters" class="pl-10 Trs-05 c-black pr-10">Service Centers</a>
                    </div>
                </div>
                <div  class="other center-flex mr-60">
                    <span class="mr-10 fw-bold Trs-03 cursor-pointer">USA</span>
                    <span class="mr-10 fw-bold Trs-03 cursor-pointer">USD</span>
                    <div class="icons p-relative d-flex">
                        <a style="color:black; padding-right:10px" asp-page="/profile"><i class="fa-sharp mr-10 cursor-pointer p-5 fa-regular bg-white rad-half fa-circle-user"></i></a>
                        <a style="color:black; padding-right:10px" asp-page="/Compare"><i class="fa-solid mr-10 p-5 fa-shuffle bg-white rad-half"></i></a>
                        <a style="color:black; padding-right:10px" asp-page="/WishList"><i class="fa-solid mr-10 p-5 fa-heart bg-white rad-half"></i></a>
                        <a style="color:black; padding-right:10px" asp-page="/CartPage"><i class="fa-solid mr-10 p-5 fa-cart-shopping bg-white rad-half"></i></a>
                        <a style="color:black; padding-right:10px; padding-top:3px;" asp-page="/Add_Car"><span>Sell car</span></a>
                        <form method="post" id="logout-from">
                            <input asp-page-handler="Logout" type="submit" style="color:black;background-color:transparent; cursor:pointer;border:none; padding-right:10px; padding-top:3px;" value="logout" />
                        </form>
                    </div>
                </div>
                
            </nav>
            <div class="in-mobile ">
                <ul class="bg-ccc Trs-05 m-0 ml--20">
                    <a class="c-black fw-bold Trs-03 pt-15 pb-15 d-block" href="#">
                    <li class="active">Promotions</li>
                    </a>
                    <a class="c-black fw-bold Trs-03 d-block pt-15 pb-15" href="#">
                    <li class="">Branches</li>
                    </a>
                    <a class="c-black fw-bold Trs-03 d-block pt-15 pb-15" href="#">
                    <li class="">Our Contacts</li>
                    </a>
                </ul>
            </div>
        </div>
    </header>
    <!-- End Navbar -->
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <!-- Start Footer -->
    <footer>
        <div class="container">
            <div class="container bg-blue w-full">
                <div class="cols ba-flex mb-20 d-block">
                    <div class="box-link mt-10 footer-box-1">
                        <h4 class="fs-18 c-white mb-10" style="width: 100%;">Service</h4>
                        <div class="fl-column d-flex mt-15 ">
                            <a href="#"><span class="fs-16 c-white d-block pb-10">Sell Car</span></a>
                            <a href="#"><span class="fs-16 c-white d-block pb-10">Buy Car</span></a>
                        </div>
                    </div>
                    <div class="box-link mt-10 footer-box-2">
                        <h4 class="fs-18 c-white mb-10" style="width: 80%;">Know more</h4>
                        <div class="fl-column d-flex mt-15 ">
                            <a href="#"><span class="fs-16 c-white d-block pb-10">Privacy Policy</span></a>
                            <a href="#"><span class="fs-16 c-white d-block pb-10">Terms of Services</span></a>
                            <a href="#"><span class="fs-16 c-white d-block">Contacts</span></a>
                        </div>
                    </div>
                    <div class="box-link mt-10 footer-box-3">
                        <h4 class="fs-18 c-white mb-10" style="width: 80%;">Categories</h4>
                        <div class="fl-column d-flex mt-15 ">
                            <a href="#"><span class="fs-16 c-white d-block pb-10">Used</span></a>
                            <a href="#"><span class="fs-16 c-white d-block pb-10">New Cars</span></a>
                            <a href="#"><span class="fs-16 c-white d-block">Accessories</span></a>
                        </div>
                    </div>
                    <div class="box-link mt-10 footer-box-4">
                        <h4 class="fs-18 c-white mb-10" style="width: 90%;">Brands</h4>
                        <div class="fl-column d-flex mt-15 ">
                            <a href="#"><span class="fs-16 c-white d-block pb-10">Nissan</span></a>
                            <a href="#"><span class="fs-16 c-white d-block pb-10">Tesla</span></a>
                            <a href="#"><span class="fs-16 c-white d-block">Jeep</span></a>
                        </div>
                    </div>
                    <div class="box-link mt-10 footer-box-5">
                        <h4 class="fs-16 c-white mb-10">Service Contacts</h4>
                        <div class="fl-column d-flex mt-15 ">
                            <a href="#"><span class="fs-16 c-white d-block pb-10">6th October</span></a>
                            <a href="#"><span class="fs-16 c-white d-block pb-10">Ismailia</span></a>
                            <a href="#"><span class="fs-16 c-white d-block">Zamalek</span></a>
                        </div>
                    </div>
                </div>
                <div class="line bn-flex">
                    <div class="social ml-15 mb-15 pl-20">
                        <span class="c-white fs-17 pr-10">Follow Us</span>
                        <a href="#"><i class="fa-brands c-white fa-whatsapp pr-5 fs-18"></i></a>
                        <a href="#"><i class="fa-brands c-white fa-facebook-f pr-5 fs-18"></i></a>
                        <a href="#"><i class="fa-brands c-white fa-youtube pr-5 fs-18"></i></a>
                        <a href="#"><i class="fa-brands c-white fa-linkedin pr-5 fs-18"></i></a>
                        <a href="#"><i class="fa-brands c-white fa-twitter pr-5 fs-18"></i></a>
                        <a href="#"><i class="fa-brands c-white fa-instagram pr-5 fs-18"></i></a>
                    </div>
                    <div class="mobile-app mr-20 pr-20">
                        <span class="c-white pr-15">Mobile App</span>
                        <a href="#"><i class="fa-brands fa-apple c-white fs-18 pr-5 "></i></a>
                        <a href="#"><i class="fa-brands fa-android c-white fs-18 "></i></a>
                    </div>
                </div>
                <span class="center-flex c-white fs-14 ">Copyright Are reserved TRMB Cars &copy; 2023</span>
            </div>
        </div>
    </footer>
    <!-- End Footer -->
</body>
</html>

Pages/Shared/adminlay.cshtml
@using MyData = System.Data
@using MyDB = Car_Store.models
@{
    // Use the MyData namespace alias instead of System.Data
    MyData.DataTable table = new MyData.DataTable();
    MyDB.DB dB = new MyDB.DB();
    string Fname = "";
    string LName = "";
    int pendingPostsNo;
    MyDB.DB db = new MyDB.DB();
    pendingPostsNo = db.getNoPendingPosts();
    if (ViewContext.HttpContext.Session.GetInt32("User_ID") == null)
    {
        Fname = "Unknown";
    }
    else
    {
        int ID = (int)ViewContext.HttpContext.Session.GetInt32("User_ID");
        table = (MyData.DataTable)dB.getAdminName(ID: ID);
        Console.WriteLine("Number of rows in table: " + table.Rows.Count);
        if (table.Rows.Count > 0)
        {
            Fname = table.Rows[0]["Fname"].ToString();
            LName = table.Rows[0]["Lname"].ToString();
        }
    }
}


<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>TRMB cars</title>
        <!-- My Style -->
        <link rel="stylesheet" href="~/css/adminlay.css" asp-append-version="true">
        <!-- Nomralize Css -->
        <link rel="stylesheet" href="~/css/normalize.css" asp-append-version="true">
        <!-- Font Awesome -->
        <link rel="stylesheet" href="~/css/all.min.css" asp-append-version="true">
        <!-- goole icons -->
        <link href="https://fonts.googleapis.com/icon?family=Material+Icons"
        rel="stylesheet">
        <!-- My FarmeWork -->
        <link rel="stylesheet" href="~/css/framework.css" asp-append-version="true">
        <!-- Font Google -->
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@400;500;700;800&display=swap" rel="stylesheet">


    </head>
    <body>
    <!--========== NAV ==========-->
    <div class="header__toggle">
        <i style="padding:20px;" class="fa-solid fa-bars bx bx-menu" id="header-toggle"></i>
        
    </div>
    <div class="nav" id="navbar">
        <nav class="nav__container">
            <div>
                <a href="/Index" class="nav__link nav__logo">
                    <!-- the icon will apear in the project -->
                    <i class="fa-sharp fa-solid fa-car-side"></i>
                    <span class="nav__logo-name">TRMB Cars</span>
                </a>

                <div class="nav__list">
                    <div class="nav__items">
                         <h3 class="nav__subtitle">@Fname @LName</h3>

                        <a asp-page="/AdminView" class="nav__link active">
                            <!-- <i class="fa-solid fa-chart-line"></i> in the bigger website -->
                            <i class='bx bx-home nav__icon'></i>
                            <span class="nav__name">Dashboard</span>
                        </a>
                        <div class="nav__dropdown">
                            <a href="#" class="nav__link">
                                <i class='bx bx-user nav__icon'></i>
                                <span class="nav__name">Manage</span>
                                <i class='bx bx-chevron-down nav__icon nav__dropdown-icon'></i>
                            </a>

                            <div class="nav__dropdown-collapse">
                                <div class="nav__dropdown-content">
                                    <a class="nav__dropdown-item" asp-page="/DisplayClients">Display Users</a>
                                    <a  class="nav__dropdown-item" asp-page="/addproduct">Add Product</a>
                                    <a  class="nav__dropdown-item" asp-page="/UpdateEmployee">Update My Data</a>
                                    <a class="nav__dropdown-item" asp-page="/AddEmployee">Add Employees</a>
                                    <a class="nav__dropdown-item" asp-page="/DisplayAllCars">Our Vehicles</a>
                                    <a  class="nav__dropdown-item" asp-page="/AdminAddCar" >Add Vehicle</a>
                                    <a  class="nav__dropdown-item" asp-page="/AddShowRoom">Show Rooms</a>
                                    <a class="nav__dropdown-item" asp-page="/ServiceCenters">Service Center</a>
                                    <a class="nav__dropdown-item" asp-page="/UpdateServiceCenters">Update Service Center</a>
                                    <a  class="nav__dropdown-item" asp-page="/AddShowRoom">Show Room</a>
                                    <a class="nav__dropdown-item"  asp-page="/AddServicesCenters">Add Service Center</a>
                                    <a class="nav__dropdown-item">Departments</a>


                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="nav__items">
                        <!-- <h3 class="nav__subtitle">Menu</h3> -->

                        <div class="nav__dropdown">
                            <a href="#" class="nav__link">
                                <i class='bx bx-bell nav__icon'></i>
                                <span class="nav__name">Notifications</span> @if(pendingPostsNo > 0){<span class="circle"></span>}
                                <i class='bx bx-chevron-down nav__icon nav__dropdown-icon'></i>
                            </a>

                            <div class="nav__dropdown-collapse">
                                <div class="nav__dropdown-content">
                                    <a asp-page="/displayPendingPosts" class="nav__dropdown-item">Pending Cars</a>
                                    <a class="nav__dropdown-item" asp-page="/DisplayOrderAdmin">Orders</a>
                                </div>
                            </div>

                        </div>
                        <div class="nav__dropdown">
                            <a  class="nav__link">
                                <i class='bx bx-bell nav__icon'></i>
                                <span class="nav__name">Statistics</span>
                                <i class='bx bx-chevron-down nav__icon nav__dropdown-icon'></i>
                            </a>

                            <div class="nav__dropdown-collapse">
                                <div class="nav__dropdown-content">
                                    <a class="nav__dropdown-item" asp-page="/AdminView" asp-fragment="sectionEmployees">Employees</a>
                                    <a class="nav__dropdown-item" asp-page="/AdminView" asp-fragment="sectionVehicles">Vehicles</a>
                                    <a class="nav__dropdown-item" asp-page="/AdminView" asp-fragment="sectionBranches">Branches</a>
                                </div>
                            </div>

                        </div>
                    </div>
                </div>
            </div>
                <form method="post">
                    <button class="logoutBtn" type="submit" sytle="padding: 0; margin-top: -45px; background: transparent; text-align: left;" asp-page-handler="Logout">
                        <li style="color:#FF0000"><i class="fa-solid fa-right-from-bracket" style="color: #FF0000"></i> Log Out</li>
                    </button>
                </form>
            </a>
        </nav>
    </div>

    <!--========== CONTENTS ==========-->
    <div class="container">
        <main role="main" class="">
            @RenderBody()
        </main>
    </div>
    <!-- Start Footer -->
    <footer>
        <div class="container">
            <div class="container bg-blue w-full">
                <div class="cols ba-flex mb-20 d-block">
                    <div class="box-link mt-10 footer-box-1">
                        <h4 class="fs-18 c-white mb-10" style="width: 100%;">Service</h4>
                        <div class="fl-column d-flex mt-15 ">
                            <a href="#"><span class="fs-16 c-white d-block pb-10">Sell Car</span></a>
                            <a href="#"><span class="fs-16 c-white d-block pb-10">Buy Car</span></a>
                        </div>
                    </div>
                    <div class="box-link mt-10 footer-box-2">
                        <h4 class="fs-18 c-white mb-10" style="width: 80%;">Know more</h4>
                        <div class="fl-column d-flex mt-15 ">
                            <a href="#"><span class="fs-16 c-white d-block pb-10">Privacy Policy</span></a>
                            <a href="#"><span class="fs-16 c-white d-block pb-10">Terms of Services</span></a>
                            <a href="#"><span class="fs-16 c-white d-block">Contacts</span></a>
                        </div>
                    </div>
                    <div class="box-link mt-10 footer-box-3">
                        <h4 class="fs-18 c-white mb-10" style="width: 80%;">Categories</h4>
                        <div class="fl-column d-flex mt-15 ">
                            <a href="#"><span class="fs-16 c-white d-block pb-10">Used</span></a>
                            <a href="#"><span class="fs-16 c-white d-block pb-10">New Cars</span></a>
                            <a href="#"><span class="fs-16 c-white d-block">Accessories</span></a>
                        </div>
                    </div>
                    <div class="box-link mt-10 footer-box-4">
                        <h4 class="fs-18 c-white mb-10" style="width: 90%;">Brands</h4>
                        <div class="fl-column d-flex mt-15 ">
                            <a href="#"><span class="fs-16 c-white d-block pb-10">Nissan</span></a>
                            <a href="#"><span class="fs-16 c-white d-block pb-10">Tesla</span></a>
                            <a href="#"><span class="fs-16 c-white d-block">Jeep</span></a>
                        </div>
                    </div>
                    <div class="box-link mt-10 footer-box-5">
                        <h4 class="fs-16 c-white mb-10">Service Contacts</h4>
                        <div class="fl-column d-flex mt-15 ">
                            <a href="#"><span class="fs-16 c-white d-block pb-10">6th October</span></a>
                            <a href="#"><span class="fs-16 c-white d-block pb-10">Ismailia</span></a>
                            <a href="#"><span class="fs-16 c-white d-block">Zamalek</span></a>
                        </div>
                    </div>
                </div>
                <div class="line bn-flex ">
                    <div class="social ml-15 mb-15 pl-20">
                        <span class="c-white fs-17 pr-10">Follow Us</span>
                        <a href="#"><i class="fa-brands c-white fa-whatsapp pr-5 fs-18"></i></a>
                        <a href="#"><i class="fa-brands c-white fa-facebook-f pr-5 fs-18"></i></a>
                        <a href="#"><i class="fa-brands c-white fa-youtube pr-5 fs-18"></i></a>
                        <a href="#"><i class="fa-brands c-white fa-linkedin pr-5 fs-18"></i></a>
                        <a href="#"><i class="fa-brands c-white fa-twitter pr-5 fs-18"></i></a>
                        <a href="#"><i class="fa-brands c-white fa-instagram pr-5 fs-18"></i></a>
                    </div>
                    <div class="mobile-app mr-20 pr-20">
                        <span class="c-white pr-15">Mobile App</span>
                        <a href="#"><i class="fa-brands fa-apple c-white fs-18 pr-5 "></i></a>
                        <a href="#"><i class="fa-brands fa-android c-white fs-18 "></i></a>
                    </div>
                </div>
                <span class="center-flex c-white fs-14 ">Copyright Are reserved TRMB Cars &copy; 2023</span>
            </div>
        </div>
    </footer>
    <script src="~/js/adminlay.js"></script>
    </body>
<!-- End Footer -->
</html>