Pages/AddEmployee.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Car_Store.models;
using System.Data;

namespace Car_Store.Pages
{
    public class AddEmployeeModel : PageModel
    {
        private readonly DB My_DB;
        [BindProperty]
        
        public DataTable dt1 {  get; set; }
        [BindProperty]
        public DataTable dt2 {  get; set; }
        [BindProperty]
        public string message { get; set; }
        public AddEmployeeModel(DB db)
        {
            My_DB = db;
            
        }

        public IActionResult OnGet(string name)
        {


            if (HttpContext.Session.GetInt32("User_Type") != 1)
            {
                return RedirectToPage("/index");
            }
            dt1 = (DataTable)My_DB.get_department_num();
            dt2 = (DataTable)My_DB.get_all_branches_num();
            return Page();
        }

        public void OnPost(string UserName,string Password,string Fname ,string Mname,string Lname,string empSSN, string Bdate,string Gender,int SuperID,string JobType,int Branch,int Salary,int UserType,int DepID) 
        { 
            My_DB.insert_emp(UserName,Fname,Mname,Lname,Password,empSSN,Bdate,Gender,Salary,SuperID,UserType,JobType,Branch, DepID);
        }
    }
}

Pages/AddServicesCenters.cshtml.cs
using Car_Store.models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Car_Store.Pages.Shared
{
    public class AddServicesCentersModel : PageModel
    {

        public ServicesCenters myCenter { get; set; }
        public IActionResult OnGet()
        {

            if (HttpContext.Session.GetInt32("User_Type") != 1)
            {
                return RedirectToPage("/index");
            }
            return Page();
        }


        public void OnPost(string name, string address, string services, decimal latitude, decimal longitude, int stars, int PhoneNumber)
        {
            myCenter = new ServicesCenters();
            myCenter.Name = name;
            myCenter.Address = address; 
            myCenter.Services = services;   
            myCenter.latitude = latitude;
            myCenter.longitude = longitude; 
            myCenter.stars = stars;
            myCenter.PhoneNumber = PhoneNumber; 
            myCenter.insert();

        }

        public IActionResult OnPostLogout()
        {
            HttpContext.Session.Remove("User_Type");
            HttpContext.Session.Remove("User_ID");
            return RedirectToPage("/Index");
        }
    }
}

Pages/CartPage.cshtml.cs
using Car_Store.models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Data;
using System.Security.Cryptography;

namespace Car_Store.Pages
{
    public class CartPageModel : PageModel
    {
        [BindProperty]
        public WishCart wc { get; set; }

        public DataTable dtCarUsed { get; set; }
        public DataTable dtCarNew { get; set; }
        public IActionResult OnGet()
        {

            if (HttpContext.Session.GetInt32("User_Type") != 0)
            {
                return RedirectToPage("/index");
            }
            wc = new WishCart();
            wc.CId= (int)HttpContext.Session.GetInt32("User_ID");
            dtCarUsed = wc.getCartUsed();
            dtCarNew = wc.getCartNew();
            return Page();
        }

        public IActionResult OnPostRemove(int pId) { 
            wc.CId = (int)HttpContext.Session.GetInt32("User_ID");
            wc.PId = pId;
            wc.delete("Cart_vehicle", "vehichle_ID");
            return RedirectToPage("/CartPage");
        }


        public IActionResult OnPostLogout()
        {
            HttpContext.Session.Remove("User_Type");
            HttpContext.Session.Remove("User_ID");
            return RedirectToPage("/Index");
        }

        public IActionResult OnPostCheckout() {
            
            return RedirectToPage("/Checkout");
        }
    }
}

Pages/DeleteClient.cshtml.cs
using Car_Store.models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Data;


namespace Car_Store.Pages.Shared
{
    public class DeleteClientModel : PageModel
    {
        public Client client { get; set; }
        public IActionResult OnGet(int ID)
        {
            if (HttpContext.Session.GetInt32("User_Type") != 1)
            {
                return RedirectToPage("/index");
            }
            client = new Client();
            client.ClientID = ID;
            return Page();
          
        }

        public IActionResult OnPostYes(int ID)
        {
            client = new Client();
            client.delete(ID);
            return RedirectToPage("/DisplayClients");
        }
        public IActionResult OnPostNo(int ID)
        {
            return RedirectToPage("/DisplayClients");
        }

        public IActionResult OnPostLogout()
        {
            HttpContext.Session.Remove("User_Type");
            HttpContext.Session.Remove("User_ID");
            return RedirectToPage("/Index");
        }


    }
}

Pages/FilterPage.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Car_Store.models;
using System.Data;
using Microsoft.SqlServer.Server;
using System.Linq;
using Microsoft.AspNetCore.Http;
using System.Runtime.InteropServices;
using System.Collections.Specialized;
using System.Drawing;

namespace Car_Store.Pages
{
    public class FilterPageModel : PageModel
    {
        [BindProperty(SupportsGet = true)]
        public string search { get; set; }
        [BindProperty]
        public List<string> Seats { get; set; }
        [BindProperty] public DataTable NumberOfSeatsAvailable { get; set; }
        [BindProperty]
        public string status { get; set; }
        [BindProperty]
        public bool Auto { get; set; }
        [BindProperty]
        public bool Manual { get; set; }
        [BindProperty]
        public WishCart cartWish { get; set; }
        public List<string> CheckedBrands { get; set; }
        public DataTable Brands { get; set; }
        [BindProperty] public DataTable Colors { get; set; }
        [BindProperty] public int ConstMinPrice { get; set; }
        [BindProperty] public int ConstMaxPrice { get; set; }

        [BindProperty] public int MinPrice { get; set; }
        [BindProperty] public int MaxPrice { get; set; }
        [BindProperty] public DataTable gearing { get; set; }
        [BindProperty] public DataTable warranty_years { get; set; }
        [BindProperty] public DataTable warranty_kilometers { get; set; }
        [BindProperty] public List<string> CheckedColors { get; set; }
        [BindProperty] public List<string> checkedWarrantyYears { get; set; }
        [BindProperty] public List<string> checkedWarrantyKilometers { get; set; }
        [BindProperty] public int selectedMIN { get; set; }
        [BindProperty] public int selectedMAX { get; set; }
        [BindProperty]
        public List<vehicle> PageCars { get; set; }
        [BindProperty]
        public DB db { get; set; }
        public FilterPageModel(DB myDatabase)
        {
            PageCars = new List<vehicle>();
            this.db = myDatabase;
            Colors = new DataTable();
            gearing = new DataTable();
            Brands = new DataTable();
            warranty_kilometers = new DataTable();
            warranty_years = new DataTable();
            CheckedBrands = new List<string>();
            //WHEN I DELETE IT IT DOESN'T WORK
            CheckedColors = new List<string>();
            checkedWarrantyYears = new List<string>();
            checkedWarrantyKilometers = new List<string>();
            cartWish = new WishCart();
            MinPrice = (int)(db.GetAvailableFilters("Price").Rows[0][1]);
            MaxPrice = (int)(db.GetAvailableFilters("Price").Rows[0][0]);
            ConstMinPrice = MinPrice;
            ConstMaxPrice = MaxPrice;
            Auto = false;
            Manual = false;
            status = "";
            Seats = new List<string>();
            NumberOfSeatsAvailable = new DataTable();
        }


        public void OnGet()
        {
            bool searchedBefore = false;
            Console.WriteLine("here with" + search); //it worked
            NumberOfSeatsAvailable = db.GetAvailableFilters("Seats");
            Brands = db.GetAvailableFilters("Brands");
            gearing = db.GetAvailableFilters("gearing");
            Colors = db.GetAvailableFilters("Colors");
            warranty_years = db.GetAvailableFilters("warranty years");
            warranty_kilometers = db.GetAvailableFilters("warranty kilometers");
            
            if (CheckedBrands.Count != 0 && CheckedColors.Count != 0 && Auto!=Manual)
            {
                PageCars = new List<vehicle>();
                foreach (string brand in CheckedBrands)
                {
                    foreach (string color in CheckedColors)
                    {
                        
                        if (Auto)
                        {
                            PageCars = PageCars.Concat(db.GetVehicles(Seats,Brand: brand, color: color, minPrice: MinPrice, maxPrice: MaxPrice,gearing:"Automatic",status:status)).ToList();
                        }
                        else
                        {
                            PageCars = PageCars.Concat(db.GetVehicles(Seats, Brand: brand, color: color, minPrice: MinPrice, maxPrice: MaxPrice ,gearing: "manual", status: status)).ToList();
                        }
                    }
                }
                return;
            }

            if (CheckedBrands.Count != 0 && CheckedColors.Count != 0)
            {
                PageCars = new List<vehicle>();
                foreach (string brand in CheckedBrands)
                {
                    foreach (string color in CheckedColors)
                    {
                        PageCars = PageCars.Concat(db.GetVehicles(Seats, Brand: brand, color: color, minPrice: MinPrice, maxPrice: MaxPrice, status: status)).ToList();
                    }
                }
                return;
            }
            else if (CheckedBrands.Count != 0 && CheckedColors.Count == 0 && Auto!=Manual)
            {
                PageCars = new List<vehicle>();
                foreach (string brand in CheckedBrands)
                {
                    if (Auto)
                    {
                        PageCars = PageCars.Concat(db.GetVehicles(Seats, Brand: brand, minPrice: MinPrice, maxPrice: MaxPrice, gearing: "Automatic", status: status)).ToList();
                    }
                    else
                    {
                        PageCars = PageCars.Concat(db.GetVehicles(Seats, Brand: brand, minPrice: MinPrice, maxPrice: MaxPrice, gearing: "manual", status: status)).ToList();
                    }
                }
                return;
            }
            else if (CheckedBrands.Count != 0 && CheckedColors.Count == 0)
            {
                PageCars = new List<vehicle>();
                foreach (string brand in CheckedBrands)
                {
                    PageCars = PageCars.Concat(db.GetVehicles(Seats, Brand: brand, minPrice: MinPrice, maxPrice: MaxPrice, status: status)).ToList();
                }
                return;
            }
            else if (CheckedColors.Count != 0 && CheckedBrands.Count == 0 && Auto!=Manual)
            {
                PageCars = new List<vehicle>();
                foreach (string color in CheckedColors)
                {
                    if (Auto)
                    {
                        PageCars = PageCars.Concat(db.GetVehicles(Seats, color: color, minPrice: MinPrice, maxPrice: MaxPrice, gearing: "Automatic", status: status)).ToList();
                    }
                    else
                    {
                        PageCars = PageCars.Concat(db.GetVehicles(Seats, color: color, minPrice: MinPrice, maxPrice: MaxPrice, gearing: "manual", status: status)).ToList();
                    }
                }
                return;
            }
            else if (CheckedColors.Count != 0 && CheckedBrands.Count == 0)
            {
                PageCars = new List<vehicle>();
                foreach (string color in CheckedColors)
                {
                    PageCars = PageCars.Concat(db.GetVehicles(Seats, color: color, minPrice: MinPrice, maxPrice: MaxPrice, status: status)).ToList();
                }
                return;
            }
            else if (Auto != Manual)
            {
                if (Auto)
                {
                    PageCars = db.GetVehicles(Seats, minPrice: MinPrice, maxPrice: MaxPrice, gearing: "Automatic", status: status);
                }
                else
                {
                    PageCars = db.GetVehicles(Seats, minPrice: MinPrice, maxPrice: MaxPrice, gearing: "Manual", status: status);
                }
            }else if (!(search == null) &&(selectedMAX != MaxPrice || selectedMIN != MinPrice))
            {                
                Console.WriteLine("here" + search + "here");
                PageCars = db.GetVehicles(Seats, Search: search, minPrice: MinPrice, maxPrice: MaxPrice, status: status);
            }
            else if(selectedMAX != MaxPrice || selectedMIN != MinPrice)
            {
                PageCars = db.GetVehicles(Seats, minPrice: MinPrice,maxPrice:MaxPrice, status: status);
            }
            else
            {
                PageCars = db.GetVehicles(Seats);
                return;
            }
        }

        public void OnPostFilter( int min_price, int max_price)
        {
            Brands = db.GetAvailableFilters("Brands");
            gearing = db.GetAvailableFilters("gearing");
            Colors = db.GetAvailableFilters("Colors");
            NumberOfSeatsAvailable = db.GetAvailableFilters("seats");
            MinPrice = min_price; MaxPrice = max_price;
            for (int i = 0; i < Brands.Rows.Count; i++)
            {
                bool isChecked = Request.Form["brand_" + i] == "on";
                if (isChecked)
                {
                    CheckedBrands.Add(Brands.Rows[i][0].ToString());
                }
            }
            for (int i = 0; i < Colors.Rows.Count; i++)
            {
                bool isChecked = Request.Form["color_" + i] == "on";
                if (isChecked)
                {
                    CheckedColors.Add(Colors.Rows[i][0].ToString());
                }
            }

            Manual = Request.Form["Manual"] == "on";
            Auto = Request.Form["Auto"] == "on";
            if (Request.Form["New"] == "on" && !(Request.Form["Used"] == "on"))
            {
                status = "new";
            }
            else if (!(Request.Form["New"] == "on") && (Request.Form["Used"] == "on"))
            {
                status = "Used";
            }
            else { status  = ""; }

            for (int i = 0; i < NumberOfSeatsAvailable.Rows.Count; i++)
            {

Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Car_Store.models;
using System.Data;
using System;
using static Org.BouncyCastle.Asn1.Cmp.Challenge;
using System.Xml.Linq;

namespace Car_Store.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;
        private readonly DB DB;
        [BindProperty(Name = "search")]
        public string search { get; set; }
        [BindProperty]
        public DataTable dt { get; set; }
        [BindProperty]
        public int iteratoe { get; set; }

        [BindProperty]
        public int Landing_random { get; set; }
        [BindProperty]
        public WishCart cartWish { get; set; }



        public IndexModel(ILogger<IndexModel> logger,DB db)
        {
            _logger = logger;
            DB = db;
        }
        public void OnGet()
        {
            
            Landing_random =DB.get_all_cars_count();
            dt = (DataTable)DB.get_all_cars();
        }

        public IActionResult OnPostLogout()
        {
            HttpContext.Session.Remove("User_Type");
            HttpContext.Session.Remove("User_ID");
            return RedirectToPage("/Index");
        }
        public IActionResult OnPostAddCarToCart(int PID)
        {
            if (HttpContext.Session.GetInt32("User_ID") == null)
            {
                return RedirectToPage("/SignUpIn");
            }
            else
            {
                cartWish.CId = (int)HttpContext.Session.GetInt32("User_ID");
            }
            cartWish.PId = PID;
            cartWish.typepv = 1;
            cartWish.typecw = 0;
            cartWish.insert();
            return RedirectToPage("/CartPage");
        }
        public IActionResult OnPostAddCarToWishList(int PID)
        {
            if (HttpContext.Session.GetInt32("User_ID") == null)
            {
                return RedirectToPage("/SignUpIn");
            }
            else
            {
                cartWish.CId = (int)HttpContext.Session.GetInt32("User_ID");
            }
            cartWish.PId = PID;
            cartWish.typepv = 1;
            cartWish.typecw = 1;
            cartWish.insert();
            return RedirectToPage("/Index");
        }
        public IActionResult OnPostSearch()
        {
            return RedirectToPage("/FilterPage", new { search = this.search });
        }
    }
}

Pages/DeleteServiceCenter.cshtml
@page
@model Car_Store.Pages.DeleteServiceCenterModel
@{

    if (HttpContext.Session.GetInt32("User_Type") == null)
    {
        Layout = "_Layout";
    }
    else if (HttpContext.Session.GetInt32("User_Type") == 0)
    {
        Layout = "ClientLayout";
    }
    else if (HttpContext.Session.GetInt32("User_Type") == 1)
    {
        Layout = "adminlay";
    }
}


<link rel="stylesheet" href="~/css/delete.css" asp-append-version="true">
<div class="content">
<div class="ask card">
    <div>
        <span>Are you sure you want to delete the service center with ID: @Model.ID ?</span>
    </div>
    <div>
        <form method="post">
            <div class="divbutton">
                <input type ="hidden" name="id" value="@Model.ID"/>
                <input style="background-color:red;" class="button" asp-page-handler="Yes" type="submit" value="Yes" />
                <input style="background-color:green;" class="button" asp-page-handler="No" type="submit" value="No" />
            </div>
        </form>
    </div>
</div>
</div>

Pages/FilterPage.cshtml
@page
@using System.Data;
@model Car_Store.Pages.FilterPageModel
@{
    if (HttpContext.Session.GetInt32("User_Type") == null)
    {
        Layout = "_Layout";
    }
    else if (HttpContext.Session.GetInt32("User_Type") == 0)
    {
        Layout = "ClientLayout";
    }
    else if (HttpContext.Session.GetInt32("User_Type") == 1)
    {
        Layout = "adminlay";
    }
}


<link rel="stylesheet" href="~/css/filter.css" asp-append-version="true">
<link />
<!-- Info before filter and cars -->
<div class="content">
<div class = "content">
<!-- end  -->
<!-- Start Best Offer -->
        <div class="filter_button" onclick="toggleWrapper()">
            <img src="~/images/filter.png" style="width:30px" />
            <h3>Filter Results</h3>
        </div>
<div class="main-container d-flex ">
    <div class="filter">
        <!-- Start Filter -->
            <form method="post" id="filter">
                    <div class="wrapper hidden">
            <div class="wd-wpb">
                <div class="widget widget sidebar-widget woocommerce widget_price_filter">
                    <h5 class="widget-title">Filter by price</h5>

                        <div class="price_slider_wrapper">
                            <div class="price_slider ui-slider ui-corner-all ui-slider-horizontal ui-widget ui-widget-content">
                                <div class="slider-track"></div>
                                    <input type="range" min="@Model.ConstMinPrice" max="@Model.ConstMaxPrice" value="@Model.MinPrice" name="min_price" id="slider-1" oninput="slideOne()">
                                    <input type="range" min="@Model.ConstMinPrice" max="@Model.ConstMaxPrice" value="@Model.MaxPrice" name="max_price" id="slider-2" oninput="slideTwo()">
                            </div>
                            <div class="price_slider_amount">
                                    <input type="text"  name="min_price" asp-for="@Model.selectedMIN" data-min="490" placeholder="Min price" style="display: none;">
                                    <input type="text" name="max_price"   data-max="13500" placeholder="Max price" style="display: none;">
                                <input type="submit" class="filter-button" value = "Filter" asp-page-handler="Filter"/>
                                <div class="price_label">
                                    Price: <span class="from" id="range1">$2,980</span> — <span class="to" id="range2">$12,650</span>
                                </div>
                            </div>
                        </div>
                </div>
                <div id="woodmart-woocommerce-layered-nav-2" class="wd-widget-collapse widget widget sidebar-widget woodmart-woocommerce-layered-nav">
                            @{
                                if (Model.Brands.Rows.Count != 0)
                                {
                                            <div class="clickable-div"> <h5 class="widget-title">Filter by Brands</h5> <i class="fa-solid fa-chevron-down select-arrow"></i> </div>
                                            <div class="wd-scroll" style="display: none;">
                                        @for (int i = 0; i < Model.Brands.Rows.Count; i++)
                                        {
                                                            <div class="mini-option">
                                                                <span>@Model.Brands.Rows[i][0].ToString()</span>
                                                                <input type="checkbox" class="tickbox" id="brand_@i" onchange="changeTickbox(this)" runat="server" name = "brand_@i">
                                                                <label for="brand_@i"></label>
                                                            </div>
                                        }
                                    </div>
                                }
                            }
                </div>
                <div id="woodmart-woocommerce-layered-nav-2" class="wd-widget-collapse widget widget sidebar-widget woodmart-woocommerce-layered-nav">
                    @{
                                
                                
                            <div class="clickable-div"> <h5 class="widget-title">Filter by Colors</h5> <i class="fa-solid fa-chevron-down select-arrow"></i> </div>
                            <div class="wd-scroll" style="display: none;">
                        @for (int i = 0; i < Model.Colors.Rows.Count; i++)
                        {
                                            <div class="mini-option">
                                                <span>@Model.Colors.Rows[i][0].ToString()</span>
                                                <input type="checkbox" class="tickbox" id="color_@i" onchange="changeTickbox(this)" runat="server" name="color_@i">
                                                <label for="color_@i"></label>
                                            </div>
                        }
                            </div>
                                
                    }
                </div>
                <div id="woodmart-woocommerce-layered-nav-2" class="wd-widget-collapse widget widget sidebar-widget woodmart-woocommerce-layered-nav">
                    @{


                        <div class="clickable-div"> <h5 class="widget-title">Other Filters</h5> <i class="fa-solid fa-chevron-down select-arrow"></i> </div>
                        <div class="wd-scroll" style="display: none;">
                            <div class="d-flex justify-content-between">
                                    <div class="mini-option">
                                            <input type="checkbox" class="tickbox" id="Manual" onchange="changeTickbox(this)" runat="server" name="Manual" onclick="toggleCheckboxes(this, 'Auto')">
                                        <label for="Manual"></label>
                                            <span>Manual</span>

                                    </div>
                                    <div class="mini-option ml-40">
                                            <input type="checkbox" class="tickbox" id="Auto" onchange="changeTickbox(this)" runat="server" name="Auto" onclick="toggleCheckboxes(this, 'Manual')">
                                        <label for="Auto"></label>
                                            <span>Automatic</span>

                                    </div>
                            </div>
                            <div class="d-flex justify-content-between">
                                <div class="mini-option">
                                    <input type="checkbox" class="tickbox" id="New" onchange="changeTickbox(this)" runat="server" name="New">
                                    <label for="New"></label>
                                    <span>New</span>

                                </div>
                                        <div class="mini-option" style="margin-left: 64px">
                                            <input type="checkbox" class="tickbox" id="Used" onchange="changeTickbox(this)" runat="server" name="Used">
                                            <label for="Used"></label>
                                            <span>Used</span>

                                </div>
                            </div>
                            <div class="d-flex justify-content-between">
                                        <h5 class="widget-title">Number of Seats</h5>
                            @for (int i = 0; i < Model.NumberOfSeatsAvailable.Rows.Count; i++)
                                        {
                                            <div class="mini-option ml-10">
                                                <input type="checkbox" class="tickbox" id="seat_@Model.NumberOfSeatsAvailable.Rows[i][0]" onchange="changeTickbox(this)" runat="server" name="seat_@Model.NumberOfSeatsAvailable.Rows[i][0]">
                                                <label for="seat_@Model.NumberOfSeatsAvailable.Rows[i][0]"></label>
                                                <span>@Model.NumberOfSeatsAvailable.Rows[i][0]</span>
                                            </div>
                                        }
                                
                            </div>
                        </div>

                    }
                </div>
            </div>
        </div>
        </form>
    </div>


            <!-- cars cards -->
    <div class="d-flex cards detials-B w-fit ml-2 gap-20">
            @for (int i = 0; i < Model.PageCars.Count; i++)
            {
                    <div class="box rad-10 bg-white Bo-Sh zooming">
                        <div class="card_image">
                        @if (Model.PageCars[i].car_status == "new")
                        {
                                        <span class="new">NEW</span>
                        }
                        else
                        {
                                        <span class="used">USED</span>
                        }

                            <a asp-page="/ProductPage" asp-route-id="@Model.PageCars[i].Id"> <img class="rad-20  pt-10 pr-10 pl-10" src="@Model.PageCars[i].car_path" alt=""> </a>

                        </div>
                    <h3 class="fs-14 pl-10">@Model.PageCars[i].Brand Model: @Model.PageCars[i].year_model</h3>
                    <div class="d-flex fl-column pl-10 mb-15 c-grey">
                        <span class="mt-20 pb-10">CC Range: @Model.PageCars[i].CC_Range</span>
                        <span class="pb-10">Gearing: @Model.PageCars[i].Gearing</span>
                        <span class="pb-10">Body Style: @Model.PageCars[i].Body_Style</span>
                    </div>
                    <div class="stars m-10">
                        <i class="fa-solid fa-star c-orange-s fs-15"></i>
                        <i class="fa-solid fa-star c-orange-s fs-15"></i>
                        <i class="fa-solid fa-star c-orange-s fs-15"></i>
                        <i class="fa-solid fa-star c-orange-s fs-15"></i>
                        <i class="fa-solid fa-star c-orange-s fs-15"></i>
                    </div>
                    <div class="stock-d d-flex fl-column">
                        @if (Model.PageCars[i].Count == 0)
                        {
                           <div class = "d-flex">
                            <i class="fa-solid fa-circle mr-5" style="color:red;padding-left:5px"></i>
                            <span class="fw-bold">Out of Stock</span>
                           </div>
                        }
                        else
                        {
                            <div class="d-flex">
                                <i class="fa-solid fa-check fa-fw yes fs-20  c-blue mr-5"></i>
                                <span class="fw-bold">In Stock</span>
                            </div>                   
                        }
                        
                        <span class="c-blue fw-bold mb-20 fs-14 ml-20 pt-10">$@Model.PageCars[i].Price</span>
                    </div>
                    <div class="A-d mr-20 ml-20">
                        <form method="post">
                            <input name="PID" value="@Model.PageCars[i].Id" type="hidden" />
                            <input asp-page-handler="AddCarToCart" class="cart-btn center-flex Bo-Sh rad-15 cursor-pointer Trs-03 c-black bg-eee pt-10 pb-10 mb-10" type="submit" value="Add to Cart" /> 
                            <input asp-page-handler="AddCarToWishList" class="cart-btn center-flex Bo-Sh rad-15 cursor-pointer Trs-03 c-black bg-eee pt-10 pb-10 mb-10" type="submit" value="Add to Wishlist" />
                        </form>
                    </div>
                </div>
            }
        </div>
    </div>
</div>
</div>
<script src="~/js/site.js"></script>

Pages/SeachBar.cshtml
@page
@model Car_Store.Pages.SeachBarModel
@{
}